############################
## CHANGE THESE
############################

baseURL: 'https://diningphil.github.io'
title: 'Federico Errica (he/him)'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'
